# Generated by Django 6.0.2 on 2026-04-01 16:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(help_text='4 буквы латиницы, например: UUEE', max_length=4, unique=True, verbose_name='ICAO код')),
                ('name', models.CharField(max_length=255, verbose_name='Название аэропорта')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(help_text='Формат: NNNN-NNNNNN', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Номер паспорта должен быть в формате NNNN-NNNNNN', regex='^\\d{4}-\\d{6}$')], verbose_name='№ паспорта')),
                ('passport_issued_by', models.CharField(max_length=255, verbose_name='Место выдачи')),
                ('passport_issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Формат: AAA-NNN, где AAA - код авиакомпании, NNN - номер', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Номер рейса должен быть в формате AAA-NNN (например, SVO-123)', regex='^[A-Z]{3}-\\d{3}$')], verbose_name='№ авиарейса')),
                ('airline_name', models.CharField(max_length=255, verbose_name='Авиакомпания')),
                ('departure_date', models.DateField(verbose_name='Дата отправления')),
                ('departure_time', models.TimeField(verbose_name='Время отправления')),
                ('total_seats', models.PositiveIntegerField(verbose_name='Всего мест')),
                ('free_seats', models.PositiveIntegerField(verbose_name='Свободных мест')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='app.airport', verbose_name='Аэропорт прибытия')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='app.airport', verbose_name='Аэропорт отправления')),
            ],
            options={
                'verbose_name': 'Авиарейс',
                'verbose_name_plural': 'Авиарейсы',
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(editable=False, help_text='Уникальный код из 6 символов (буквы+цифры)', max_length=10, unique=True, verbose_name='Код бронирования')),
                ('booked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.flight', verbose_name='Авиарейс')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.passenger', verbose_name='Пассажир')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-booked_at'],
            },
        ),
    ]
